In [2]:
%matplotlib inline
import numpy as np

This notebook shows some basic linear algebra operations in python. We will use the linear algebra package in numpy. Detailed documentation can be found in this [link](https://numpy.org/doc/stable/reference/routines.linalg.html).

# Vector Operation

## Dot product

In [4]:
# real vectors
a = [1, 2, 3]
b = [4, 5, 6]
print(np.dot(a, b))   # a dot b = 1*4 + 2*5 + 3*6

32


In [12]:
# complex vectors
a = [1 + 1j*2, 3 + 1j*0.5]
b = [2, 4]
print(np.dot(a, b))
print(np.dot(a, np.conj(a)))    # conjugate np.conj(a)

(14+6j)
(14.25+0j)


# Matrix

## Multiplication

In [40]:
A = np.array([[1, 3],
              [2, 1]])
B = np.array([[4, 1],
              [2, 2]])
# AB != BA
print("AB = \n", np.matmul(A, B))
print("BA = \n", np.matmul(B, A))

AB = 
 [[10  7]
 [10  4]]
BA = 
 [[ 6 13]
 [ 6  8]]


In [7]:
A = np.array([[1, 3, 1],
              [2, 1, 2]])
B = np.array([[4, 1],
              [2, 2],
              [7, 3]])
print("A: ", A.shape, ", B: ", B.shape)
# AB != BA
print("AB = \n", np.matmul(A, B))
print("BA = \n", np.matmul(B, A))

A:  (2, 3) , B:  (3, 2)
AB = 
 [[17 10]
 [24 10]]
BA = 
 [[ 6 13  6]
 [ 6  8  6]
 [13 24 13]]


## Determinant

In [34]:
A = np.array([[1, 2],
              [3, 4]])
print("det(A) = {0:.4f}".format(np.linalg.det(A)))

det(A) = -2.0000


In [27]:
A = np.array([[1, 2, 1],
              [2, 1, 2],
              [1, 3, 5]])
print("det(A) = {0:.4f}".format(np.linalg.det(A)))

det(A) = -12.0000


In [39]:
A = np.random.random([5, 5])   # A random 5x5 matrix
print("A = \n", A)
print("det(A) = {0:.4e}".format(np.linalg.det(A)))

A = 
 [[0.66256845 0.60613486 0.47901177 0.80617231 0.96572358]
 [0.19805615 0.24488297 0.72388203 0.71806928 0.86286768]
 [0.2035298  0.59217327 0.53214529 0.50248273 0.51221843]
 [0.88706332 0.30856039 0.03144379 0.35329682 0.19947292]
 [0.81130369 0.91927654 0.95341325 0.17231004 0.17855831]]
det(A) = 5.0781e-02


## Inverse

In [47]:
A = np.array([[1, 2],
              [3, 4]])
Ainv = np.linalg.inv(A)
print("A = \n", A)
print("A^{-1} = \n", Ainv)
print("AA^{-1} = \n", np.matmul(A, Ainv))

A = 
 [[1 2]
 [3 4]]
A^{-1} = 
 [[-2.   1. ]
 [ 1.5 -0.5]]
AA^{-1} = 
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [52]:
A = np.random.random([4, 4])  # A random 4x4 matrix
Ainv = np.linalg.inv(A)
print("A = \n", A)
print("A^{-1} = \n", Ainv)
print("AA^{-1} = \n", np.matmul(A, Ainv))

A = 
 [[0.51569824 0.97295332 0.92175356 0.90322376]
 [0.49612086 0.39725633 0.56649612 0.75596808]
 [0.94554264 0.34914985 0.41996602 0.24895468]
 [0.11941324 0.01001992 0.67117948 0.81664216]]
A^{-1} = 
 [[-0.80212643  1.13482166  0.95711546 -0.45511693]
 [ 1.03955188  0.62978167 -0.705754   -1.51760722]
 [ 1.71558216 -5.80283887  1.73715634  2.94465963]
 [-1.30546194  4.59555418 -1.55902354 -1.11045189]]
AA^{-1} = 
 [[ 1.00000000e+00  2.79736854e-17 -5.78355408e-17 -4.20489116e-16]
 [ 1.58799451e-16  1.00000000e+00 -4.41103901e-17 -8.98327183e-17]
 [ 1.18724884e-16  8.96674783e-17  1.00000000e+00  1.97853978e-16]
 [ 7.56426313e-18 -2.83768799e-16 -1.00773357e-16  1.00000000e+00]]
